// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foqbocabjvmuqapbitiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvcWJvY2FianZtdXFhcGJpdGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDIyNzIsImV4cCI6MjA2Njk3ODI3Mn0.Pa_WAGGcR7mZ78Bs62Fh0YpgtCZStJJBg61ukA9R5C0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});